version: '3.5'
services:
  kafka-setup:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: kafka-setup
    networks:
      - server-deployment_confluent

networks:
  server-deployment_confluent:
    external: true